spring:
  application:
    name: spring-boot-jpa
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: create
  datasource:
    database: MYSQL
    continue-on-error: false
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/syf?useSSL=false
    username: root
    password: 123456

server:
  port: 9090